source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'

gem 'rails', '~> 6.0.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'jwt'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.5'
gem 'redis', '~> 4.0'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors', :require => 'rack/cors'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'unidecoder'
gem 'dbview_cti'

gem 'httparty'
gem 'webpacker'
gem 'react_on_rails', '11.1.4'
gem 'jsTimezoneDetect-rails'
gem 'mailgun-ruby', '~>1.1.6'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'faker'
gem 'jquery-rails'
gem 'sentry-raven'
gem 'slack-notifier'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'factory_bot_rails', '~> 4.0'
  gem 'meta_request'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'annotate'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  gem 'capistrano-yarn',    require: false
  gem 'ed25519', '~> 1.2'
  gem 'bcrypt_pbkdf', '~> 1'
end

group :test do
  gem 'capybara', '>= 2.3', '< 4.0'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'phantomjs'
  gem 'poltergeist'
  gem 'simplecov'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'mini_racer', platforms: :ruby